


// 用户相关

export const SET_USER_ACCOUNT = 'SET_USER_ACCOUNT'
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_FRIEND_LIST = 'SET_FRIEND_LIST'
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT'
export const SET_FRIEND_REQUEST = 'SET_FRIEND_REQUEST'

// 书房相关
export const SET_BOOKROOM_USER_INFO = 'SET_BOOKROOM_USER_INFO'
export const SET_BOOK_LIST = 'SET_BOOK_LIST'
export const SET_BOOK_SELECTED = 'SET_BOOK_SELECTED'


// socket相关
export const SOCKET_CONNECT = 'SOCKET_CONNECT'
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT'
export const SOCKET_BORROWREQUST = 'SOCKET_BORROWREQUST'
export const SOCKET_TEXTMESSAGE = 'SOCKET_TEXTMESSAGE'



// chat 相关
export const SET_BORROW_REQUESTS = 'SET_BORROW_REQUESTS'
export const SET_CHATROOM_USER_INFO = 'SET_CHATROOM_USER_INFO'
export const SET_CHAT_RECORDS = 'SET_CHAT_RECORDS'
